# Analysis of multi-target sgRNAs by Fortin et al, 2019

the counts decay exponentially as the number of perfect alignments increases. 68,742 guides align uniquely to one target only, and 3959 guides align to more than one target (multi-target guides), resulting in 2023 genes that are targeted by at least one multi-target guide.

68742 + 3959 = 72701

```{r}
library(tidyverse)

avana_alignment <- read_csv('../object_intermediate/STable_02_AvanaLibrary_aln.csv') %>%
  filter(!str_detect(gene, fixed("NO_CURRENT")))

avana_alignment_fortin <- read_csv('13059_2019_1621_MOESM3_ESM.csv')

length(unique(avana_alignment$sgrna))
# unique number of sgRNA = 70941

avana_alignment_0 <- avana_alignment %>%
  filter(n.mismatches == 0) %>%
  select(sgrna, gene_id, targetedGene)

multi_target <- avana_alignment_0 %>%
  count(sgrna, targetedGene)
  
  
```

```{r}

library(crisprBowtie)
library(GenomicRanges)
library(AnnotationDbi)
library(GenomicFeatures)
library(AnnotationDbi)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(org.Hs.eg.db)
library(tidyverse)

source("../sgRNA_library_refinement_pipeline_functions.R")


ccds_filename_dir <- "CCDS_20250112.txt"

library_alignment <- read_csv('../object_intermediate/sample_M2_150K_aln.csv')
list_chromosome <- paste0("chr", c(1:22, "X", "Y"))
library_alignment <- library_alignment %>%
  filter(chr %in% list_chromosome | is.na(chr))

length(unique(library_alignment$sgRNA))

library_alignment <- library_alignment %>%
  drop_na()

gr <- GRanges(
  seqnames = library_alignment$chr,
  ranges = IRanges(start = library_alignment$pam_site, width = 1),
  strand = library_alignment$strand
)


txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
genes <- genes(txdb)

hits <- findOverlaps(gr, genes)

library_alignment$target_gene_id <- NA
library_alignment$target_gene_id[queryHits(hits)] <- names(genes)[subjectHits(hits)]

library_alignment$target_gene_symbol <- mapIds(
  org.Hs.eg.db,
  keys = library_alignment$target_gene_id,
  column = "SYMBOL",
  keytype = "ENTREZID",
  multiVals = "first"
)

# multi-target sgRNAs mistakenly removed from the analysis

mismatch_zero_mistakenly_removed <- library_alignment %>% 
  filter(n_mismatches == 0 & gene == target_gene_symbol) %>%
  count(sgRNA) %>%
  filter(n > 1)

alignment_data_mistakenly_removed <- library_alignment %>%
  filter(n_mismatches == 0 ) %>%
  filter(sgRNA %in% mismatch_zero_mistakenly_removed$sgRNA)



```

