---
title: "Backup Code of multi_target_sgrna_analysis"
output: github_document
---
# A venn diagram function to compare the similarity between three libraries

```{r}

venn_diagram <- function(set1, set2, name_set1, name_set2, color1, color2, name_venn) {
  only_set1 <- length(setdiff(set1, set2))
  only_set2 <- length(setdiff(set2, set1))
  both_sets  <- length(intersect(set1, set2))

  totalset1 <- only_set1 + both_sets
  totalset2 <- only_set2 + both_sets

  pct_set1 <- round((only_set1 / totalset1) * 100, 2)
  pct_set2 <- round((only_set2 / totalset2) * 100, 2)
  pct_overlap_set1 <- round((both_sets / totalset1) * 100, 2)
  pct_overlap_set2 <- round((both_sets / totalset2) * 100, 2)

  sgRNA_similarity <- venn.diagram(
        x = list(set1, set2),
        category.names = c(name_set1, name_set2),
        filename = NULL,  
        fill = c(color1, color2),
        alpha = 0.5,
        cex = 0,  # Set text size to 0 to hide numbers
        cat.cex = 0.75,  # Set category label size
        cat.pos = c(-2, 2),  # Adjust category label positions
        cat.dist = c(0.05, 0.05),  # Adjust category label distances
        lwd = 2
  )

  png(filename = name_venn, width = 1250, height = 1250, res = 300)
  grid.newpage()
  grid.draw(sgRNA_similarity)

  grid.text(label = paste0(only_set2, '\n', pct_set1, '%'), x = 0.25, y = 0.50, gp = gpar(fontsize = 10))
  grid.text(label = paste0(only_set1, '\n', pct_set2, '%'), x = 0.75, y = 0.50, gp = gpar(fontsize = 10))
  grid.text(label = paste0(pct_overlap_set1, '%', '\nor\n', pct_overlap_set2, '%'), x = 2.5, y = 0.50, gp = gpar(fontsize = 7))

  dev.off()
}


```

# compare the similarity of all sequences between three libraries

```{r}
venn_diagram(brunello$spacer, toronto$spacer, "Brunello \n 77K sgRNAs", "Toronto V3 \n 71K sgRNAs", 'powderblue', 'mistyrose', 'VennDiagram_sgRNAs_brunello_toronto.png')
venn_diagram(brunello$spacer, cellecta$spacer, "Brunello \n 77K sgRNAs", "Cellecta \n 150K sgRNAs", 'powderblue', 'lightgreen', 'VennDiagram_sgRNAs_brunello_cellecta.png') 
venn_diagram(toronto$spacer, cellecta$spacer, "Toronto V3 \n 77K sgRNAs", "Cellecta \n 150K sgRNAs", 'mistyrose', 'lightgreen', 'VennDiagram_sgRNAs_toronto_cellecta.png') 
```

